nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173', 'http://localhost:5174']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE', 'PATCH']
        expose_headers: ['Link', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173', 'http://localhost:5174']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE', 'PATCH']
            allow_credentials: true
            expose_headers: ['Link', 'Authorization']
            max_age: 3600
